### ISSUE TITLE
Make Recipes and Fuels Not Being Loaded By Default More Noticeable on the Wiki.

### ISSUE THREAD

**Issue by ItsSchatten** [ShaneBeeStudios/VirtualFurnace#1]
**Is your feature request related to a problem? Please describe.**

Stumbled around for well about an hour before realizing that the API does not register recipes or fuels be default, even took the long way around and messed around with the API via my own fork.

**Describe the solution you'd like**

Make information about recipes or fuels being loaded by default on the wiki more noticable, perhaps in bold letters on the main page.

**Describe alternatives you've considered**

Register all vanilla recipes and fuels by default within the API, should still allow for plugins to register their custom fuels and recipes, if it does not Solution #1 is the only valid option.

**Additional context**

N/A

**Comment by ShaneBeee** [comment]
Better?

<img width="1143" alt="Screen Shot 2020-08-21 at 8 00 23 PM" src="https://user-images.githubusercontent.com/20008482/90947225-080a4f80-e3e9-11ea-9144-5725f0220676.png">

**Comment by ItsSchatten** [comment]
Much! Thanks.

**Comment by ShaneBeee** [comment]
You're welcome 👍
